FROM eclipse-temurin:21 AS build
WORKDIR /app

# Gradle 캐싱을 위해 먼저 필요한 파일들만 복사
COPY build.gradle.kts settings.gradle.kts gradlew /app/
COPY gradle /app/gradle/

# Gradle 종속성 미리 다운로드
RUN ./gradlew dependencies

# 전체 소스 코드 복사 및 애플리케이션 빌드
COPY . /app
RUN ./gradlew build

# Stage 2: Runtime Stage
FROM eclipse-temurin:21
WORKDIR /app

# 빌드된 JAR 파일 복사
COPY --from=build /app/build/libs/*.jar app.jar

# 실행 명령어
ENTRYPOINT ["java", "-jar", "/app/app.jar"]

EXPOSE 8000